# Generated by Django 5.2 on 2025-04-03 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название города')),
                ('description', models.TextField(max_length=500, verbose_name='Описание города')),
                ('cuisine', models.TextField(max_length=1200, verbose_name='Кухня')),
                ('photo_cuisine', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография кухни страны/города')),
                ('what_to_see', models.TextField(max_length=1200, verbose_name='Что посмотреть')),
                ('photo_what_to_see', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография достопремичательностей страны/города')),
                ('when_is_the_season', models.TextField(max_length=1200, verbose_name='Когда сезон?')),
                ('photo_when_is_the_season', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фото сезона страны/города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=50, verbose_name='Электронная почта')),
                ('message_subject', models.CharField(max_length=50, verbose_name='Тема сообщения')),
                ('message', models.TextField(max_length=1200, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='SmallContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='CountryTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Название страны')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LikTour.cities', verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Страна и её города',
                'verbose_name_plural': 'Страны и их города',
            },
        ),
    ]
