# Generated by Django 5.2 on 2025-04-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrytour',
            name='country_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Картинка страны'),
        ),
    ]
