# Generated by Django 5.2 on 2025-04-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0002_countrytour_country_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrytour',
            name='city',
        ),
        migrations.AddField(
            model_name='countrytour',
            name='cities',
            field=models.ManyToManyField(to='LikTour.cities', verbose_name='Названия городов'),
        ),
    ]
