# Generated by Django 5.2 on 2025-04-05 07:19

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0003_remove_countrytour_city_countrytour_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='smallcontactform',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
    ]
