# Generated by Django 5.2 on 2025-04-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0004_alter_contactform_telephone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutNewsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Заголовок новости в отдельной странице')),
                ('first_info', models.TextField(max_length=1200, verbose_name='Первый блок с новостью')),
                ('first_info_phoro', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография для 1 блока с новостью на странице')),
                ('second_info', models.TextField(max_length=1200, verbose_name='Второй блок с новостью')),
                ('second_info_photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография для 2 блока с новостью на странице')),
                ('third_info', models.TextField(max_length=1200, verbose_name='Третий блок с новостью')),
                ('third_info_photo', models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография для 3 блока с новостью на странице')),
            ],
            options={
                'verbose_name': 'Новость отдельно',
                'verbose_name_plural': 'Новости отдельно',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, verbose_name='Заголовок новости')),
                ('description', models.TextField(max_length=145, verbose_name='Описание новости')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LikTour.aboutnewspage', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Новость блоком',
                'verbose_name_plural': 'Новости блоком',
            },
        ),
    ]
