# Generated by Django 5.2 on 2025-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0005_aboutnewspage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutnewspage',
            name='first_title',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Заголовок первого блока'),
        ),
        migrations.AddField(
            model_name='aboutnewspage',
            name='second_title',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Заголовок второго блока'),
        ),
        migrations.AddField(
            model_name='aboutnewspage',
            name='third_title',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Заголовок третьего блока'),
        ),
    ]
