# Generated by Django 5.2 on 2025-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0006_aboutnewspage_first_title_aboutnewspage_second_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytour',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, to='LikTour.cities', verbose_name='Названия городов'),
        ),
    ]
