# Generated by Django 5.2 on 2025-04-05 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0007_alter_countrytour_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LikTour.aboutnewspage', verbose_name='Новость'),
        ),
    ]
