# Generated by Django 5.2 on 2025-04-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0008_alter_news_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', verbose_name='Фотография города'),
        ),
        migrations.AlterField(
            model_name='aboutnewspage',
            name='first_info',
            field=models.TextField(max_length=340, verbose_name='Первый блок с новостью'),
        ),
        migrations.AlterField(
            model_name='aboutnewspage',
            name='second_info',
            field=models.TextField(max_length=340, verbose_name='Второй блок с новостью'),
        ),
        migrations.AlterField(
            model_name='aboutnewspage',
            name='third_info',
            field=models.TextField(max_length=340, verbose_name='Третий блок с новостью'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='cuisine',
            field=models.TextField(max_length=340, verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='description',
            field=models.TextField(max_length=340, verbose_name='Описание города'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='what_to_see',
            field=models.TextField(max_length=340, verbose_name='Что посмотреть'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='when_is_the_season',
            field=models.TextField(max_length=340, verbose_name='Когда сезон?'),
        ),
    ]
