# Generated by Django 5.2 on 2025-04-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0009_cities_city_photo_alter_aboutnewspage_first_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок баннера')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='Подзаголовок баннера')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка на подробности')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order'],
            },
        ),
    ]
