# Generated by Django 5.2 on 2025-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0010_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrytour',
            name='cities',
            field=models.ManyToManyField(blank=True, to='LikTour.cities', verbose_name='Названия городов'),
        ),
    ]
