# Generated by Django 5.2 on 2025-04-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0011_alter_countrytour_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закрепить новость'),
        ),
    ]
