# Generated by Django 5.2 on 2025-04-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0012_news_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallcontactform',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LikTour.cities', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smallcontactform',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LikTour.countrytour', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
