# Generated by Django 5.2 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LikTour', '0013_smallcontactform_city_smallcontactform_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallcontactform',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='smallcontactform',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
    ]
